// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVcKA5jsZ7JzT6g4yDXcHVhb_GnEzD3I0',
    appId: '1:653787070399:web:cf9a6763e8b3429fc1eb0a',
    messagingSenderId: '653787070399',
    projectId: 'teste-direct-solution',
    authDomain: 'teste-direct-solution.firebaseapp.com',
    storageBucket: 'teste-direct-solution.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6iZKp7Yu1wAGRVvL5cS5O6D8PcLm3_T8',
    appId: '1:653787070399:android:1127a27bc6872e07c1eb0a',
    messagingSenderId: '653787070399',
    projectId: 'teste-direct-solution',
    storageBucket: 'teste-direct-solution.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9nVfh0BPIreCfUl2ZXq2l9cA3E6xX7LA',
    appId: '1:653787070399:ios:df598ccea44f71fbc1eb0a',
    messagingSenderId: '653787070399',
    projectId: 'teste-direct-solution',
    storageBucket: 'teste-direct-solution.firebasestorage.app',
    iosBundleId: 'com.example.testeFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9nVfh0BPIreCfUl2ZXq2l9cA3E6xX7LA',
    appId: '1:653787070399:ios:df598ccea44f71fbc1eb0a',
    messagingSenderId: '653787070399',
    projectId: 'teste-direct-solution',
    storageBucket: 'teste-direct-solution.firebasestorage.app',
    iosBundleId: 'com.example.testeFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVcKA5jsZ7JzT6g4yDXcHVhb_GnEzD3I0',
    appId: '1:653787070399:web:9545c48c2264b6dfc1eb0a',
    messagingSenderId: '653787070399',
    projectId: 'teste-direct-solution',
    authDomain: 'teste-direct-solution.firebaseapp.com',
    storageBucket: 'teste-direct-solution.firebasestorage.app',
  );
}
